language: python
deploy:
  provider: heroku
  api_key:
    secure: "EHfrLBE+PFah0F4w4pERAcIsj6XPHNKMyv8AbBlkXgHm5jIX4jG3+B09NWVcFWTO7JQWipS8WmhocUAI9zAH8iqXk7TWc22O6+9h+G8tBqnvfuk+apjA14dMDSMA4fsnP4bzsG1zRywFqX6AG4v9HT6qacgkucp4Mwk2TU8KgeM33YU5V5Emle3xBxjHVozi9bs8QFXR4MVSORBuNfBY8oidPMyoJlRczWHWkB+CEJYAL1I3kjILKpU78SVZevUqUys1tK7m5CAEidAy3+Su2RjqOuKtovW7Y1paBnaE8jULYYPJjT/E+tPPp4vHIO9XfGU1ApkjUTnig3xljn6ioH6Cppj1cj3OoYjR2AtPSzaM+tzrF33uogCLul54TCstQRxoUbYPNLstqn37kRHaMuIDT8OLVzsfdUn5ZgV+iuPkS3JxVcUt1OTuE4foNzM4uKl3uEopOv7wkprWaeNYNksSz3K87oy/mLynQ4x567Bk8CrgfhsZSQpEHd0Cqg5TfnlnSvaaN/w0v16ZZ+8vhC1agsYPTJ4wkg+yHn2GRwn6bZCdwvan9kXe6dRkfmTqoBQdi7j3BqOhV3AizsMQc2xgZm7bKArpdvOVy8AVyy5BgThYjYa1AsBMnO8g5lJlyhZbdiFhoHPMwJNbO6YLqwzXgdUulGsl1SMDT7Sv1e4="
  app: marinakeu-urlshortener
  on:
    repo: marinakeu/urlshortener