language: python
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: mRhLA9X8rm21/Lp93U4kf8p+Mzyxbo2WySp/BOfWLXIW6jcOvMRG71qjWJWDXxP8+cE+lRnfJNnhEONP/YSO1k8YdRBjnkg5V2/1EnCe2YnVx0LaLiqw0jlT/LfIWK5kAEzcmY0i83tJvbuIrerjO5246jyaRaD1r0XYE6aT2ENHLYydXDMyvhdAIXvga1ziFK0nZceA1/5wUjQZF+zDbN9xaWv+mwq2596efGr/PSOw+JnyzyUyFKObd15y0xkMTH/zOemkE9T6499n/ZWwBT8p35KqTLsciEsIM8gwLj8Gfw3V5670ebusrAqYetiBhPue8CoZNnn2GkkZQqynJaBpffy+3GCjdNq9YS84VmYObtYTNbTm9EuBXIxJl1sy1RnLj4rmm3kkHZemUdqXNNi+SUPuB6JPOCFloxD2t5Gp341vxy8kG81rKxTMZ4eOCyEJ5tkB4QgyKqc1rQ/AQdo0q+0HWHFWpGNXoOwd40yxjPWgfHfDJf1y/X2m769WtxSIJpdOBi3g5+CfTglxK6H4717dS0sGsH24rPZeX1HoxIbUPcd14mpzKKFaV3qJx/eV95V85LPw04MNQHPqGmKeWg08O5ewk92Wa/Llv3sSVlCDpeagRJJJ0mBbo8vMqBF/+smVF5nt4LkByyIQwOXH0i7D4inHGImz/XZwadI=
  app: marinakeu-urlshortener
  on:
    repo: marinakeu/urlshortener
script:
- pytest
